parameters:
      ez_rest.controller.content.class: Ez\RestBundle\Rest\Controller\ContentController
      ez_rest.content.content.class: Ez\RestBundle\Rest\Content\Content
      ez_rest.content.contenttype.class: Ez\RestBundle\Rest\Content\ContentType
      ez_rest.value_object_visitor.content.class: Ez\RestBundle\Rest\ValueObjectVisitor\ContentData
services:
    ez_rest.content.content:
        class: '%ez_rest.content.content.class%'
        arguments:
            - '@ezpublish.urlalias_router'
            - '@ezpublish.api.service.location'
            - '@ezpublish.api.service.search'
            - '@ezpublish.api.service.content_type'
            - '@ezpublish.api.service.field_type'
            - '@ezpublish.fieldtype.ezrichtext.converter.output.xhtml5.core'
            - '@ezpublish.image_alias.imagine.alias_generator'
        calls:
            - [setSiteAccess, [@ezpublish.siteaccess]]
    ez_rest.content.contenttype:
        class: '%ez_rest.content.contenttype.class%'
        parent: 'ez_rest.content.content'
    ez_rest.controller.content:
        class: '%ez_rest.controller.content.class%'
        arguments:
            - '@ez_rest.content.contenttype'
        parent: ezpublish_rest.controller.base
    ez_rest.value_object_visitor.content:
        parent: ezpublish_rest.output.value_object_visitor.base
        class: '%ez_rest.value_object_visitor.content.class%'
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: Ez\RestBundle\Rest\Values\ContentData }