parameters:
      ez_rest.controller.content.class: Ez\RestDemoBundle\Controller\ContentTypeContentListController
      ez_rest.content.content.class: Ez\RestDemoBundle\Content\Content
      ez_rest.content.contenttype.class: Ez\RestDemoBundle\Content\ContentType
      ez_rest.value_object_visitor.content.class: Ez\RestDemo\Rest\ValueObjectVisitor\ContentData
      ez_rest.input_parser.contenttypecontentlist.class: Ez\RestDemo\Rest\Input\Parser\ContentTypeContentList
      ##use service to handle post and get handler
      ez_rest.request_data_parser.service.class: Ez\RestDemo\Rest\Repository\RequestParserService
      ez_rest.request_data_parser.gethandler.class: Ez\RestDemo\Rest\Repository\HeaderMethodParserHandler\GetRequestDataHandler
      ez_rest.request_data_parser.posthandler.class: Ez\RestDemo\Rest\Repository\HeaderMethodParserHandler\PostRequestDataHandler

      ez_rest.controller.content_create.class: Ez\RestDemoBundle\Controller\CreateContentController
      ez_rest.content_create.service.class: Ez\RestDemoBundle\CreateContentServices\CreateContent
      ez_rest.content_create.rest_client.class: Ez\RestDemoBundle\CreateContentServices\RestClient
      ez_rest.content_create.parser.class: Ez\RestDemoBundle\CreateContentServices\Parser
      ez_rest.content_create.guzzle_http_client.class: GuzzleHttp\Client
      ez_rest.content_create.cookieJar.class: GuzzleHttp\Cookie\CookieJar
      ez_rest.content_create.host: 'http://cologne.tripandtravel.local'

services:
    ez_rest.controller.content:
        class: '%ez_rest.controller.content.class%'
        parent: ezpublish_rest.controller.base
        arguments:
            - '@ez_rest.content.contenttype'
            - '@ez_rest.request_data_parser.service'
    ez_rest.content.content:
        class: '%ez_rest.content.content.class%'
        arguments:
            - '@ezpublish.urlalias_router'
            - '@ezpublish.api.service.location'
            - '@ezpublish.api.service.search'
            - '@ezpublish.api.service.content_type'
            - '@ezpublish.api.service.field_type'
            - '@ezpublish.fieldtype.ezrichtext.converter.output.xhtml5.core'
            - '@ezpublish.image_alias.imagine.alias_generator'
        calls:
            - [setSiteAccess, [@ezpublish.siteaccess]]
    ez_rest.content.contenttype:
        class: '%ez_rest.content.contenttype.class%'
        parent: 'ez_rest.content.content'
        #parent: ezpublish_rest.controller.base
    ez_rest.value_object_visitor.content:
        parent: ezpublish_rest.output.value_object_visitor.base
        class: '%ez_rest.value_object_visitor.content.class%'
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: Ez\RestDemo\Rest\Values\ContentData }
    ez_rest.input_parser.contenttypecontentlist:
        parent: ezpublish_rest.input.parser
        class: '%ez_rest.input_parser.contenttypecontentlist.class%'
        tags:
            - { name: ezpublish_rest.input.parser, mediaType: application/vnd.custom.ContentTypeContentList }
    ##use service to handle post and get handler
    ez_rest.request_data_parser.service:
        class: '%ez_rest.request_data_parser.service.class%'
        calls:
            - [setSiteAccess, ['@ezpublish.siteaccess']]
            - [setInputDispatcher, ['@ezpublish_rest.input.dispatcher']]
    ez_rest.request_data_parser.gethandler:
        class: '%ez_rest.request_data_parser.gethandler.class%'
        tags:
            - {name: ez_rest.request_data.contenttype_contentlist, alias: GET  }
    ez_rest.request_data_parser.posthandler:
        class: '%ez_rest.request_data_parser.posthandler.class%'
        tags:
            - {name: ez_rest.request_data.contenttype_contentlist, alias: POST }

    #Create Content
    ez_rest.controller.content_create:
        class: '%ez_rest.controller.content_create.class%'
        parent: ezpublish_rest.controller.base
        arguments:
            - '@ez_rest.content_create.service'

    ez_rest.content_create.service:
        class: '%ez_rest.content_create.service.class%'
        arguments:
            - '@ez_rest.content_create.rest_client'

    ez_rest.content_create.guzzle_http_client:
        class: '%ez_rest.content_create.guzzle_http_client.class%'

    ez_rest.content_create.cookieJar:
        class: '%ez_rest.content_create.cookieJar.class%'

    ez_rest.content_create.rest_client:
        class: '%ez_rest.content_create.rest_client.class%'
        arguments:
            - '@ez_rest.content_create.guzzle_http_client'
            - '@ez_rest.content_create.cookieJar'
        calls:
            - [setHttpHost, ['%ez_rest.content_create.host%']]

